### PR TITLE
Refactored SDL2_image and SDL2_mixer minus the documentation.

### PR DESCRIPTION
**Pull request by Blizzardo1**

### CODE REVIEW

**Comment by Blizzardo1** [comment]
If someone wants to continue this project, then I can spend more time helping, else what's the point of working with a project with the last commit being 2 years ago?

**Comment by GeorchW** [comment]
Sorry, didn't see your MR for a while. Sure, feel free to work on this! I kinda moved away from the C#/.NET platform a while ago, but I'm happy that my code is useful to some. Since this is just a wrapper, the code shouldn't really age as long as SDL itself is not changing its interface (which it hasn't done for years IIRC).

On the MR itself: Could you update the status table in the README.md?

**Comment by Blizzardo1** [comment]
I've updated the README.md in regards to current working status

**Comment by GeorchW** [comment]
Thx!

**Pull request merged**
