### PR TITLE
Updates to SDL_ttf.cs

### PR DESCRIPTION
**Pull request by Blizzardo1**
I've completed the documentation portion and brought the codebase up to SDL v2.28.0. The rest of the codebase will need to begin migrating to the new SDL3 base eventually.

### CODE REVIEW

**Comment by Blizzardo1** [comment]
@GeorchW Happy New Year!

**Comment by GeorchW** [comment]
LGTM in general. If you could clean up the .gitignore, I can pull this

**Comment by Blizzardo1** [comment]
I"ll update the .gitignore. If I may ask, what should be added/modified/deleted?

**Comment by GeorchW** [comment]
See the review: I think it's enough to just ignore the `.vs/` folder entirely (by writing `.vs/` instead of `/.vs`). Then you can remove all the entries starting with `.vs` below.

**Comment by Blizzardo1** [comment]
Sorry it took so long. Here's the fix.

**Pull request merged**
